# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_0_controller
    - arm_1_controller
    - arm_0_gripper_controller
    - arm_1_gripper_controller

  arm_0_controller:
    type: FollowJointTrajectory
    joints:
      - arm_0_shoulder_pan_joint
      - arm_0_shoulder_lift_joint
      - arm_0_elbow_joint
      - arm_0_wrist_1_joint
      - arm_0_wrist_2_joint
      - arm_0_wrist_3_joint
  arm_1_controller:
    type: FollowJointTrajectory
    joints:
      - arm_1_shoulder_pan_joint
      - arm_1_shoulder_lift_joint
      - arm_1_elbow_joint
      - arm_1_wrist_1_joint
      - arm_1_wrist_2_joint
      - arm_1_wrist_3_joint
  arm_0_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - arm_0_gripper_robotiq_85_left_knuckle_joint
  arm_1_gripper_controller:
    type: FollowJointTrajectory
    joints:
      - arm_1_gripper_robotiq_85_left_knuckle_joint